class Word < ApplicationRecord


	validates :untranslated_word, presence: true
	validates :translated_word, presence: true
	default_scope { order(common_rank: :asc) }

	include PgSearch
	pg_search_scope :search_engine, :against => [:translated_word]
	scope :translated_word, -> (input_translated_word) { where("translated_word ILIKE ?", "%#{input_translated_word}%") }
	
	def self.spanish_populate(language, current_user)
		Word.create([{language: language, user_id: current_user.id, common_rank:1, untranslated_word:"de", translated_word: "of"},
		{language: language, user_id: current_user.id, common_rank:2, untranslated_word:"que", translated_word: "that"},
		{language: language, user_id: current_user.id, common_rank:3, untranslated_word:"no", translated_word: "not"},
		{language: language, user_id: current_user.id, common_rank:4, untranslated_word:"a", translated_word: "to"},
		{language: language, user_id: current_user.id, common_rank:5, untranslated_word:"la", translated_word: "the"},
		{language: language, user_id: current_user.id, common_rank:6, untranslated_word:"el", translated_word: "the"},
		{language: language, user_id: current_user.id, common_rank:7, untranslated_word:"y", translated_word: "and"},
		{language: language, user_id: current_user.id, common_rank:8, untranslated_word:"es", translated_word: "this"},
		{language: language, user_id: current_user.id, common_rank:9, untranslated_word:"en", translated_word: "in"},
		{language: language, user_id: current_user.id, common_rank:10, untranslated_word: "lo", translated_word:"it"},
		{language: language, user_id: current_user.id, common_rank:11, untranslated_word: "un", translated_word:"a"},
		{language: language, user_id: current_user.id, common_rank:12, untranslated_word: "qué", translated_word:"what"},
		{language: language, user_id: current_user.id, common_rank:13, untranslated_word: "por", translated_word:"by"},
		{language: language, user_id: current_user.id, common_rank:14, untranslated_word: "me", translated_word:"me"},
		{language: language, user_id: current_user.id, common_rank:15, untranslated_word: "una", translated_word:"a"},
		{language: language, user_id: current_user.id, common_rank:16, untranslated_word: "te", translated_word:"you"},
		{language: language, user_id: current_user.id, common_rank:17, untranslated_word: "se", translated_word:"is"},
		{language: language, user_id: current_user.id, common_rank:18, untranslated_word: "los", translated_word:"the"},
		{language: language, user_id: current_user.id, common_rank:19, untranslated_word: "con", translated_word:"with"},
		{language: language, user_id: current_user.id, common_rank:20, untranslated_word: "para", translated_word:"to"},
		{language: language, user_id: current_user.id, common_rank:21, untranslated_word: "mi", translated_word:"my"},
		{language: language, user_id: current_user.id, common_rank:22, untranslated_word: "está", translated_word:"is"},
		{language: language, user_id: current_user.id, common_rank:23, untranslated_word: "si", translated_word:"if"},
		{language: language, user_id: current_user.id, common_rank:24, untranslated_word: "sí", translated_word:"yes"},
		{language: language, user_id: current_user.id, common_rank:25, untranslated_word: "pero", translated_word:"but"},
		{language: language, user_id: current_user.id, common_rank:26, untranslated_word: "bien", translated_word:"well"},
		{language: language, user_id: current_user.id, common_rank:27, untranslated_word: "las", translated_word:"the"},
		{language: language, user_id: current_user.id, common_rank:28, untranslated_word: "yo", translated_word:"I"},
		{language: language, user_id: current_user.id, common_rank:29, untranslated_word: "su", translated_word:"its"},
		{language: language, user_id: current_user.id, common_rank:30, untranslated_word: "eso", translated_word:"that"},
		{language: language, user_id: current_user.id, common_rank:31, untranslated_word: "aquí", translated_word:"here"},
		{language: language, user_id: current_user.id, common_rank:32, untranslated_word: "del", translated_word:"the"},
		{language: language, user_id: current_user.id, common_rank:33, untranslated_word: "al", translated_word:"to the"},
		{language: language, user_id: current_user.id, common_rank:34, untranslated_word: "como", translated_word:"as"},
		{language: language, user_id: current_user.id, common_rank:35, untranslated_word: "le", translated_word:"you"},
		{language: language, user_id: current_user.id, common_rank:36, untranslated_word: "tu", translated_word:"your"},
		{language: language, user_id: current_user.id, common_rank:37, untranslated_word: "más", translated_word:"more"},
		{language: language, user_id: current_user.id, common_rank:38, untranslated_word: "todo", translated_word:"everything"},
		{language: language, user_id: current_user.id, common_rank:39, untranslated_word: "ya", translated_word:"already"},
		{language: language, user_id: current_user.id, common_rank:40, untranslated_word: "muy", translated_word:"very"},
		{language: language, user_id: current_user.id, common_rank:41, untranslated_word: "esto", translated_word:"this"},
		{language: language, user_id: current_user.id, common_rank:42, untranslated_word: "vamos", translated_word:"we"},
		{language: language, user_id: current_user.id, common_rank:43, untranslated_word: "ahora", translated_word:"now"},
		{language: language, user_id: current_user.id, common_rank:44, untranslated_word: "ha", translated_word:"has"},
		{language: language, user_id: current_user.id, common_rank:45, untranslated_word: "esta", translated_word:"this"},
		{language: language, user_id: current_user.id, common_rank:46, untranslated_word: "hay", translated_word:"there"},
		{language: language, user_id: current_user.id, common_rank:47, untranslated_word: "algo", translated_word:"something"},
		{language: language, user_id: current_user.id, common_rank:48, untranslated_word: "estoy", translated_word:"am"},
		{language: language, user_id: current_user.id, common_rank:49, untranslated_word: "tú", translated_word:"you"},
		{language: language, user_id: current_user.id, common_rank:50, untranslated_word: "tengo", translated_word:"I have"},
		{language: language, user_id: current_user.id, common_rank:51, untranslated_word: "así", translated_word:"so"},
		{language: language, user_id: current_user.id, common_rank:52, untranslated_word: "nada", translated_word:"nothing"},
		{language: language, user_id: current_user.id, common_rank:53, untranslated_word: "nos", translated_word:"us"},
		{language: language, user_id: current_user.id, common_rank:54, untranslated_word: "cuando", translated_word:"when"},
		{language: language, user_id: current_user.id, common_rank:55, untranslated_word: "cómo", translated_word:"how"},
		{language: language, user_id: current_user.id, common_rank:56, untranslated_word: "sé", translated_word:"know"},
		{language: language, user_id: current_user.id, common_rank:57, untranslated_word: "él", translated_word:"he"},
		{language: language, user_id: current_user.id, common_rank:58, untranslated_word: "estás", translated_word:"are"},
		{language: language, user_id: current_user.id, common_rank:59, untranslated_word: "sólo", translated_word:"only"},
		{language: language, user_id: current_user.id, common_rank:60, untranslated_word: "o", translated_word:"or"},
		{language: language, user_id: current_user.id, common_rank:61, untranslated_word: "quiero", translated_word:"I want"},
		{language: language, user_id: current_user.id, common_rank:62, untranslated_word: "gracias", translated_word:"thanks"},
		{language: language, user_id: current_user.id, common_rank:63, untranslated_word: "tiene", translated_word:"you have"},
		{language: language, user_id: current_user.id, common_rank:64, untranslated_word: "este", translated_word:"this"},
		{language: language, user_id: current_user.id, common_rank:65, untranslated_word: "soy", translated_word:"am"},
		{language: language, user_id: current_user.id, common_rank:66, untranslated_word: "he", translated_word:"I"},
		{language: language, user_id: current_user.id, common_rank:67, untranslated_word: "puedo", translated_word:"I can"},
		{language: language, user_id: current_user.id, common_rank:68, untranslated_word: "bueno", translated_word:"good"},
		{language: language, user_id: current_user.id, common_rank:69, untranslated_word: "era", translated_word:"era"},
		{language: language, user_id: current_user.id, common_rank:70, untranslated_word: "ser", translated_word:"be"},
		{language: language, user_id: current_user.id, common_rank:71, untranslated_word: "vez", translated_word:"time"},
		{language: language, user_id: current_user.id, common_rank:72, untranslated_word: "hacer", translated_word:"do"},
		{language: language, user_id: current_user.id, common_rank:73, untranslated_word: "todos", translated_word:"everyone"},
		{language: language, user_id: current_user.id, common_rank:74, untranslated_word: "fue", translated_word:"was"},
		{language: language, user_id: current_user.id, common_rank:75, untranslated_word: "son", translated_word:"are"},
		{language: language, user_id: current_user.id, common_rank:76, untranslated_word: "ella", translated_word:"she"},
		{language: language, user_id: current_user.id, common_rank:77, untranslated_word: "eres", translated_word:"you are"},
		{language: language, user_id: current_user.id, common_rank:78, untranslated_word: "usted", translated_word:"you"},
		{language: language, user_id: current_user.id, common_rank:79, untranslated_word: "tienes", translated_word:"you have"},
		{language: language, user_id: current_user.id, common_rank:80, untranslated_word: "puede", translated_word:"can"},
		{language: language, user_id: current_user.id, common_rank:81, untranslated_word: "señor", translated_word:"Mr."},
		{language: language, user_id: current_user.id, common_rank:82, untranslated_word: "quién", translated_word:"who"},
		{language: language, user_id: current_user.id, common_rank:83, untranslated_word: "ese", translated_word:"that"},
		{language: language, user_id: current_user.id, common_rank:84, untranslated_word: "voy", translated_word:"I"},
		{language: language, user_id: current_user.id, common_rank:85, untranslated_word: "creo", translated_word:"I"},
		{language: language, user_id: current_user.id, common_rank:86, untranslated_word: "casa", translated_word:"home"},
		{language: language, user_id: current_user.id, common_rank:87, untranslated_word: "porque", translated_word:"because"},
		{language: language, user_id: current_user.id, common_rank:88, untranslated_word: "hola", translated_word:"hello"},
		{language: language, user_id: current_user.id, common_rank:89, untranslated_word: "tan", translated_word:"so"},
		{language: language, user_id: current_user.id, common_rank:90, untranslated_word: "favor", translated_word:"favor"},
		{language: language, user_id: current_user.id, common_rank:91, untranslated_word: "dónde", translated_word:"where"},
		{language: language, user_id: current_user.id, common_rank:92, untranslated_word: "sus", translated_word:"their"},
		{language: language, user_id: current_user.id, common_rank:93, untranslated_word: "dos", translated_word:"two"},
		{language: language, user_id: current_user.id, common_rank:94, untranslated_word: "nunca", translated_word:"never"},
		{language: language, user_id: current_user.id, common_rank:95, untranslated_word: "sabes", translated_word:"know"},
		{language: language, user_id: current_user.id, common_rank:96, untranslated_word: "verdad", translated_word:"truth"},
		{language: language, user_id: current_user.id, common_rank:97, untranslated_word: "quieres", translated_word:"want"},
		{language: language, user_id: current_user.id, common_rank:98, untranslated_word: "mucho", translated_word:"much"},
		{language: language, user_id: current_user.id, common_rank:99, untranslated_word: "mí", translated_word:"me"},
		{language: language, user_id: current_user.id, common_rank:100, untranslated_word: "tiempo", translated_word: "time"}])
	end

	def self.french_populate(language, current_user)
		Word.create([{user_id: current_user.id, language: language, common_rank:1, untranslated_word:"je", translated_word:"I"},
		{user_id: current_user.id, language: language, common_rank:2, untranslated_word:"de", translated_word:"of"},
		{user_id: current_user.id, language: language, common_rank:3, untranslated_word:"est", translated_word:"is"},
		{user_id: current_user.id, language: language, common_rank:4, untranslated_word:"pas", translated_word:"not"},
		{user_id: current_user.id, language: language, common_rank:5, untranslated_word:"le", translated_word:"the"},
		{user_id: current_user.id, language: language, common_rank:6, untranslated_word:"vous", translated_word:"you"},
		{user_id: current_user.id, language: language, common_rank:7, untranslated_word:"la", translated_word:"the"},
		{user_id: current_user.id, language: language, common_rank:8, untranslated_word:"tu", translated_word:"you"},
		{user_id: current_user.id, language: language, common_rank:9, untranslated_word:"que", translated_word:"that"},
		{user_id: current_user.id, language: language, common_rank:10, untranslated_word: "un", translated_word:"a"},
		{user_id: current_user.id, language: language, common_rank:11, untranslated_word: "il", translated_word:"it"},
		{user_id: current_user.id, language: language, common_rank:12, untranslated_word: "et", translated_word:"and"},
		{user_id: current_user.id, language: language, common_rank:13, untranslated_word: "à", translated_word:"with"},
		{user_id: current_user.id, language: language, common_rank:14, untranslated_word: "a", translated_word:"has"},
		{user_id: current_user.id, language: language, common_rank:15, untranslated_word: "ne", translated_word:"only"},
		{user_id: current_user.id, language: language, common_rank:16, untranslated_word: "les", translated_word:"the"},
		{user_id: current_user.id, language: language, common_rank:17, untranslated_word: "ce", translated_word:"this"},
		{user_id: current_user.id, language: language, common_rank:18, untranslated_word: "en", translated_word:"in"},
		{user_id: current_user.id, language: language, common_rank:19, untranslated_word: "on", translated_word:"on"},
		{user_id: current_user.id, language: language, common_rank:20, untranslated_word: "ça", translated_word:"that"},
		{user_id: current_user.id, language: language, common_rank:21, untranslated_word: "une", translated_word:"one"},
		{user_id: current_user.id, language: language, common_rank:22, untranslated_word: "ai", translated_word:"have"},
		{user_id: current_user.id, language: language, common_rank:23, untranslated_word: "pour", translated_word:"of"},
		{user_id: current_user.id, language: language, common_rank:24, untranslated_word: "des", translated_word:"of"},
		{user_id: current_user.id, language: language, common_rank:25, untranslated_word: "moi", translated_word:"me"},
		{user_id: current_user.id, language: language, common_rank:26, untranslated_word: "qui", translated_word:"which"},
		{user_id: current_user.id, language: language, common_rank:27, untranslated_word: "nous", translated_word:"we"},
		{user_id: current_user.id, language: language, common_rank:28, untranslated_word: "y", translated_word:"there"},
		{user_id: current_user.id, language: language, common_rank:29, untranslated_word: "mais", translated_word:"but"},
		{user_id: current_user.id, language: language, common_rank:30, untranslated_word: "me", translated_word:"me"},
		{user_id: current_user.id, language: language, common_rank:31, untranslated_word: "dans", translated_word:"in"},
		{user_id: current_user.id, language: language, common_rank:32, untranslated_word: "du", translated_word:"the"},
		{user_id: current_user.id, language: language, common_rank:33, untranslated_word: "bien", translated_word:"well"},
		{user_id: current_user.id, language: language, common_rank:34, untranslated_word: "elle", translated_word:"she"},
		{user_id: current_user.id, language: language, common_rank:35, untranslated_word: "si", translated_word:"if"},
		{user_id: current_user.id, language: language, common_rank:36, untranslated_word: "tout", translated_word:"while"},
		{user_id: current_user.id, language: language, common_rank:37, untranslated_word: "plus", translated_word:"more"},
		{user_id: current_user.id, language: language, common_rank:38, untranslated_word: "non", translated_word:"not"},
		{user_id: current_user.id, language: language, common_rank:39, untranslated_word: "mon", translated_word:"my"},
		{user_id: current_user.id, language: language, common_rank:40, untranslated_word: "suis", translated_word:"am"},
		{user_id: current_user.id, language: language, common_rank:41, untranslated_word: "te", translated_word:"you"},
		{user_id: current_user.id, language: language, common_rank:42, untranslated_word: "au", translated_word:"to"},
		{user_id: current_user.id, language: language, common_rank:43, untranslated_word: "avec", translated_word:"with"},
		{user_id: current_user.id, language: language, common_rank:44, untranslated_word: "va", translated_word:"will"},
		{user_id: current_user.id, language: language, common_rank:45, untranslated_word: "oui", translated_word:"yes"},
		{user_id: current_user.id, language: language, common_rank:46, untranslated_word: "toi", translated_word:"you"},
		{user_id: current_user.id, language: language, common_rank:47, untranslated_word: "fait", translated_word:"fact"},
		{user_id: current_user.id, language: language, common_rank:48, untranslated_word: "ils", translated_word:"they"},
		{user_id: current_user.id, language: language, common_rank:49, untranslated_word: "as", translated_word:"have"},
		{user_id: current_user.id, language: language, common_rank:50, untranslated_word: "être", translated_word:"be"},
		{user_id: current_user.id, language: language, common_rank:51, untranslated_word: "faire", translated_word:"to"},
		{user_id: current_user.id, language: language, common_rank:52, untranslated_word: "se", translated_word:"to"},
		{user_id: current_user.id, language: language, common_rank:53, untranslated_word: "comme", translated_word:"such as"},
		{user_id: current_user.id, language: language, common_rank:54, untranslated_word: "était", translated_word:"was"},
		{user_id: current_user.id, language: language, common_rank:55, untranslated_word: "sur", translated_word:"about"},
		{user_id: current_user.id, language: language, common_rank:56, untranslated_word: "quoi", translated_word:"what"},
		{user_id: current_user.id, language: language, common_rank:57, untranslated_word: "ici", translated_word:"here"},
		{user_id: current_user.id, language: language, common_rank:58, untranslated_word: "sais", translated_word:"know"},
		{user_id: current_user.id, language: language, common_rank:59, untranslated_word: "lui", translated_word:"him"},
		{user_id: current_user.id, language: language, common_rank:60, untranslated_word: "veux", translated_word:"want"},
		{user_id: current_user.id, language: language, common_rank:61, untranslated_word: "ma", translated_word:"my"},
		{user_id: current_user.id, language: language, common_rank:62, untranslated_word: "là", translated_word:"there"},
		{user_id: current_user.id, language: language, common_rank:63, untranslated_word: "rien", translated_word:"nothing"},
		{user_id: current_user.id, language: language, common_rank:64, untranslated_word: "dit", translated_word:"said"},
		{user_id: current_user.id, language: language, common_rank:65, untranslated_word: "es", translated_word:"es"},
		{user_id: current_user.id, language: language, common_rank:66, untranslated_word: "où", translated_word:"where"},
		{user_id: current_user.id, language: language, common_rank:67, untranslated_word: "votre", translated_word:"your"},
		{user_id: current_user.id, language: language, common_rank:68, untranslated_word: "pourquoi", translated_word:"why"},
		{user_id: current_user.id, language: language, common_rank:69, untranslated_word: "sont", translated_word:"are"},
		{user_id: current_user.id, language: language, common_rank:70, untranslated_word: "cette", translated_word:"this"},
		{user_id: current_user.id, language: language, common_rank:71, untranslated_word: "quand", translated_word:"when"},
		{user_id: current_user.id, language: language, common_rank:72, untranslated_word: "par", translated_word:"by"},
		{user_id: current_user.id, language: language, common_rank:73, untranslated_word: "son", translated_word:"its"},
		{user_id: current_user.id, language: language, common_rank:74, untranslated_word: "ton", translated_word:"your"},
		{user_id: current_user.id, language: language, common_rank:75, untranslated_word: "peux", translated_word:"can"},
		{user_id: current_user.id, language: language, common_rank:76, untranslated_word: "vais", translated_word:"will"},
		{user_id: current_user.id, language: language, common_rank:77, untranslated_word: "dire", translated_word:"say"},
		{user_id: current_user.id, language: language, common_rank:78, untranslated_word: "alors", translated_word:"then"},
		{user_id: current_user.id, language: language, common_rank:79, untranslated_word: "comment", translated_word:"how"},
		{user_id: current_user.id, language: language, common_rank:80, untranslated_word: "avez", translated_word:"have"},
		{user_id: current_user.id, language: language, common_rank:81, untranslated_word: "bon", translated_word:"good"},
		{user_id: current_user.id, language: language, common_rank:82, untranslated_word: "ou", translated_word:"or"},
		{user_id: current_user.id, language: language, common_rank:83, untranslated_word: "très", translated_word:"highly"},
		{user_id: current_user.id, language: language, common_rank:84, untranslated_word: "merci", translated_word:"thank you"},
		{user_id: current_user.id, language: language, common_rank:85, untranslated_word: "ont", translated_word:"have"},
		{user_id: current_user.id, language: language, common_rank:86, untranslated_word: "même", translated_word:"same"},
		{user_id: current_user.id, language: language, common_rank:87, untranslated_word: "jamais", translated_word:"never"},
		{user_id: current_user.id, language: language, common_rank:88, untranslated_word: "aussi", translated_word:"also"},
		{user_id: current_user.id, language: language, common_rank:89, untranslated_word: "voir", translated_word:"watch"},
		{user_id: current_user.id, language: language, common_rank:90, untranslated_word: "chose", translated_word:"thing"},
		{user_id: current_user.id, language: language, common_rank:91, untranslated_word: "allez", translated_word:"will"},
		{user_id: current_user.id, language: language, common_rank:92, untranslated_word: "tous", translated_word:"every"},
		{user_id: current_user.id, language: language, common_rank:93, untranslated_word: "deux", translated_word:"two"},
		{user_id: current_user.id, language: language, common_rank:94, untranslated_word: "ces", translated_word:"these"},
		{user_id: current_user.id, language: language, common_rank:95, untranslated_word: "faut", translated_word:"must"},
		{user_id: current_user.id, language: language, common_rank:96, untranslated_word: "sa", translated_word:"its"},
		{user_id: current_user.id, language: language, common_rank:97, untranslated_word: "êtes", translated_word:"are"},
		{user_id: current_user.id, language: language, common_rank:98, untranslated_word: "été", translated_word:"summer"},
		{user_id: current_user.id, language: language, common_rank:99, untranslated_word: "ta", translated_word:"your"},
		{user_id: current_user.id, language: language, common_rank:100, untranslated_word:"fais", translated_word:"do"}])
	end

	def self.german_populate(language, current_user)
		Word.create([{user_id: current_user.id, language: language, common_rank:1, untranslated_word:	"ich", translated_word: "I"},
		{user_id: current_user.id, language: language, common_rank:2, untranslated_word:	"sie", translated_word: "they"},
		{user_id: current_user.id, language: language, common_rank:3, untranslated_word:	"das", translated_word: "the"},
		{user_id: current_user.id, language: language, common_rank:4, untranslated_word:	"ist", translated_word: "is"},
		{user_id: current_user.id, language: language, common_rank:5, untranslated_word:	"du", translated_word: "you"},
		{user_id: current_user.id, language: language, common_rank:6, untranslated_word:	"nicht", translated_word: "not"},
		{user_id: current_user.id, language: language, common_rank:7, untranslated_word:	"die", translated_word: "the"},
		{user_id: current_user.id, language: language, common_rank:8, untranslated_word:	"und", translated_word: "and"},
		{user_id: current_user.id, language: language, common_rank:9, untranslated_word:	"es", translated_word: "it"},
		{user_id: current_user.id, language: language, common_rank:10, untranslated_word: "der", translated_word: "the"},
		{user_id: current_user.id, language: language, common_rank:11, untranslated_word: "was", translated_word: "what"},
		{user_id: current_user.id, language: language, common_rank:12, untranslated_word: "wir", translated_word: "we"},
		{user_id: current_user.id, language: language, common_rank:13, untranslated_word: "er", translated_word: "he"},
		{user_id: current_user.id, language: language, common_rank:14, untranslated_word: "zu", translated_word: "to"},
		{user_id: current_user.id, language: language, common_rank:15, untranslated_word: "ein", translated_word: "one"},
		{user_id: current_user.id, language: language, common_rank:16, untranslated_word: "in", translated_word: "in"},
		{user_id: current_user.id, language: language, common_rank:17, untranslated_word: "mit", translated_word: "with"},
		{user_id: current_user.id, language: language, common_rank:18, untranslated_word: "mir", translated_word: "me"},
		{user_id: current_user.id, language: language, common_rank:19, untranslated_word: "den", translated_word: "the"},
		{user_id: current_user.id, language: language, common_rank:20, untranslated_word: "wie", translated_word: "as"},
		{user_id: current_user.id, language: language, common_rank:21, untranslated_word: "ja", translated_word: "yes"},
		{user_id: current_user.id, language: language, common_rank:22, untranslated_word: "auf", translated_word: "onto"},
		{user_id: current_user.id, language: language, common_rank:23, untranslated_word: "mich", translated_word: "myself"},
		{user_id: current_user.id, language: language, common_rank:24, untranslated_word: "so", translated_word: "so"},
		{user_id: current_user.id, language: language, common_rank:25, untranslated_word: "eine", translated_word: "one"},
		{user_id: current_user.id, language: language, common_rank:26, untranslated_word: "aber", translated_word: "however"},
		{user_id: current_user.id, language: language, common_rank:27, untranslated_word: "hier", translated_word: "here"},
		{user_id: current_user.id, language: language, common_rank:28, untranslated_word: "sind", translated_word: "are"},
		{user_id: current_user.id, language: language, common_rank:29, untranslated_word: "für", translated_word: "for"},
		{user_id: current_user.id, language: language, common_rank:30, untranslated_word: "von", translated_word: "from"},
		{user_id: current_user.id, language: language, common_rank:31, untranslated_word: "haben", translated_word: "have"},
		{user_id: current_user.id, language: language, common_rank:32, untranslated_word: "dich", translated_word: "you"},
		{user_id: current_user.id, language: language, common_rank:33, untranslated_word: "hat", translated_word: "has"},
		{user_id: current_user.id, language: language, common_rank:34, untranslated_word: "dass", translated_word: "that"},
		{user_id: current_user.id, language: language, common_rank:35, untranslated_word: "war", translated_word: "was"},
		{user_id: current_user.id, language: language, common_rank:36, untranslated_word: "wenn", translated_word: "when"},
		{user_id: current_user.id, language: language, common_rank:37, untranslated_word: "an", translated_word: "to"},
		{user_id: current_user.id, language: language, common_rank:38, untranslated_word: "nein", translated_word: "no"},
		{user_id: current_user.id, language: language, common_rank:39, untranslated_word: "da", translated_word: "because"},
		{user_id: current_user.id, language: language, common_rank:40, untranslated_word: "noch", translated_word: "more"},
		{user_id: current_user.id, language: language, common_rank:41, untranslated_word: "bin", translated_word: "am"},
		{user_id: current_user.id, language: language, common_rank:42, untranslated_word: "habe", translated_word: "have"},
		{user_id: current_user.id, language: language, common_rank:43, untranslated_word: "nur", translated_word: "only"},
		{user_id: current_user.id, language: language, common_rank:44, untranslated_word: "dir", translated_word: "you"},
		{user_id: current_user.id, language: language, common_rank:45, untranslated_word: "sich", translated_word: "themselves"},
		{user_id: current_user.id, language: language, common_rank:46, untranslated_word: "ihr", translated_word: "their"},
		{user_id: current_user.id, language: language, common_rank:47, untranslated_word: "einen", translated_word: "a"},
		{user_id: current_user.id, language: language, common_rank:48, untranslated_word: "uns", translated_word: "to us"},
		{user_id: current_user.id, language: language, common_rank:49, untranslated_word: "dem", translated_word: "the"},
		{user_id: current_user.id, language: language, common_rank:50, untranslated_word: "hast", translated_word: "have"},
		{user_id: current_user.id, language: language, common_rank:51, untranslated_word: "ihn", translated_word: "it"},
		{user_id: current_user.id, language: language, common_rank:52, untranslated_word: "aus", translated_word: "from"},
		{user_id: current_user.id, language: language, common_rank:53, untranslated_word: "kann", translated_word: "can"},
		{user_id: current_user.id, language: language, common_rank:54, untranslated_word: "gut", translated_word: "good"},
		{user_id: current_user.id, language: language, common_rank:55, untranslated_word: "im", translated_word: "in"},
		{user_id: current_user.id, language: language, common_rank:56, untranslated_word: "schon", translated_word: "already"},
		{user_id: current_user.id, language: language, common_rank:57, untranslated_word: "auch", translated_word: "also"},
		{user_id: current_user.id, language: language, common_rank:58, untranslated_word: "sein", translated_word: "its"},
		{user_id: current_user.id, language: language, common_rank:59, untranslated_word: "jetzt", translated_word: "now"},
		{user_id: current_user.id, language: language, common_rank:60, untranslated_word: "meine", translated_word: "my"},
		{user_id: current_user.id, language: language, common_rank:61, untranslated_word: "mal", translated_word: "times"},
		{user_id: current_user.id, language: language, common_rank:62, untranslated_word: "dann", translated_word: "then"},
		{user_id: current_user.id, language: language, common_rank:63, untranslated_word: "als", translated_word: "than"},
		{user_id: current_user.id, language: language, common_rank:64, untranslated_word: "um", translated_word: "to"},
		{user_id: current_user.id, language: language, common_rank:65, untranslated_word: "s", translated_word: "s"},
		{user_id: current_user.id, language: language, common_rank:66, untranslated_word: "mein", translated_word: "my"},
		{user_id: current_user.id, language: language, common_rank:67, untranslated_word: "bist", translated_word: "are"},
		{user_id: current_user.id, language: language, common_rank:68, untranslated_word: "doch", translated_word: "but"},
		{user_id: current_user.id, language: language, common_rank:69, untranslated_word: "wird", translated_word: "is"},
		{user_id: current_user.id, language: language, common_rank:70, untranslated_word: "keine", translated_word: "no"},
		{user_id: current_user.id, language: language, common_rank:71, untranslated_word: "lch", translated_word: "I"},
		{user_id: current_user.id, language: language, common_rank:72, untranslated_word: "nach", translated_word: "after"},
		{user_id: current_user.id, language: language, common_rank:73, untranslated_word: "alles", translated_word: "everything"},
		{user_id: current_user.id, language: language, common_rank:74, untranslated_word: "man", translated_word: "to"},
		{user_id: current_user.id, language: language, common_rank:75, untranslated_word: "oder", translated_word: "or"},
		{user_id: current_user.id, language: language, common_rank:76, untranslated_word: "nichts", translated_word: "nothing"},
		{user_id: current_user.id, language: language, common_rank:77, untranslated_word: "wo", translated_word: "where"},
		{user_id: current_user.id, language: language, common_rank:78, untranslated_word: "weiß", translated_word: "white"},
		{user_id: current_user.id, language: language, common_rank:79, untranslated_word: "werden", translated_word: "will"},
		{user_id: current_user.id, language: language, common_rank:80, untranslated_word: "will", translated_word: "wants"},
		{user_id: current_user.id, language: language, common_rank:81, untranslated_word: "mehr", translated_word: "more"},
		{user_id: current_user.id, language: language, common_rank:82, untranslated_word: "warum", translated_word: "why"},
		{user_id: current_user.id, language: language, common_rank:83, untranslated_word: "ihnen", translated_word: "them"},
		{user_id: current_user.id, language: language, common_rank:84, untranslated_word: "etwas", translated_word: "something"},
		{user_id: current_user.id, language: language, common_rank:85, untranslated_word: "bitte", translated_word: "please"},
		{user_id: current_user.id, language: language, common_rank:86, untranslated_word: "bei", translated_word: "with"},
		{user_id: current_user.id, language: language, common_rank:87, untranslated_word: "muss", translated_word: "must"},
		{user_id: current_user.id, language: language, common_rank:88, untranslated_word: "hab", translated_word: "have"},
		{user_id: current_user.id, language: language, common_rank:89, untranslated_word: "immer", translated_word: "always"},
		{user_id: current_user.id, language: language, common_rank:90, untranslated_word: "los", translated_word: "Go"},
		{user_id: current_user.id, language: language, common_rank:91, untranslated_word: "mann", translated_word: "man"},
		{user_id: current_user.id, language: language, common_rank:92, untranslated_word: "vor", translated_word: "ago"},
		{user_id: current_user.id, language: language, common_rank:93, untranslated_word: "oh", translated_word: "oh"},
		{user_id: current_user.id, language: language, common_rank:94, untranslated_word: "zum", translated_word: "to"},
		{user_id: current_user.id, language: language, common_rank:95, untranslated_word: "sehr", translated_word: "highly"},
		{user_id: current_user.id, language: language, common_rank:96, untranslated_word: "sehen", translated_word: "watch"},
		{user_id: current_user.id, language: language, common_rank:97, untranslated_word: "sagen", translated_word: "say"},
		{user_id: current_user.id, language: language, common_rank:98, untranslated_word: "wieder", translated_word: "again"},
		{user_id: current_user.id, language: language, common_rank:99, untranslated_word: "alle", translated_word: "All"},
		{user_id: current_user.id, language: language, common_rank:100, untranslated_word: "gehen", translated_word: "move"}])
	end

end
